"""
This file was created by Sebastian Gruenwald on 14.11.2024, Neuhausen am Rheinfall.

Contact:
  - Email: sebiscodes@gmail.com

Social Links:
  - GitHub: https://github.com/sebiscodes
  - Instagram: https://www.instagram.com/sebisprojects/
  - YouTube: https://www.youtube.com/@sebisprojects
  - Linktree: https://linktr.ee/sebisprojects

Note: Comments were generated by ChatGPT
"""

from SHLSEncoder import SHLSEncoder
# Example usage of the SHLSEncoder class
# Data structure to encode
data = {
    "Company": {
        "ID": "1001",
        "Name": "Tech Solutions Inc.",
        "Founded": "2008",
        "Location": "New York, USA",
        "Departments": [
            {
                "DepartmentID": "001",
                "DepartmentName": "Development",
                "Employees": [
                    {
                        "EmployeeID": "1001",
                        "Name": "Alice Smith",
                        "Role": "Software Engineer",
                        "Salary": "90000",
                        "StartDate": "2019-06-01",
                        "FullTime": "true"
                    },
                    {
                        "EmployeeID": "1002",
                        "Name": "Bob Johnson",
                        "Role": "Data Scientist",
                        "Salary": "95000",
                        "StartDate": "2020-02-15",
                        "FullTime": "true"
                    }
                ]
            },
            {
                "DepartmentID": "002",
                "DepartmentName": "Human Resources",
                "Employees": [
                    {
                        "EmployeeID": "2001",
                        "Name": "Carol White",
                        "Role": "HR Specialist",
                        "Salary": "60000",
                        "StartDate": "2021-09-10",
                        "FullTime": "true"
                    },
                    {
                        "EmployeeID": "2002",
                        "Name": "David Brown",
                        "Role": "Recruiter",
                        "Salary": "55000",
                        "StartDate": "2018-11-05",
                        "FullTime": "false"
                    }
                ]
            }
        ]
    },
    "Financials": [
        {"Year": "2021", "Revenue": "5000000", "Expenses": "3500000", "NetProfit": "1500000"},
        {"Year": "2022", "Revenue": "5200000", "Expenses": "3700000", "NetProfit": "1500000"}
    ]
}

# Initialize the SHLSEncoder
encoder = SHLSEncoder()

# Encode the data structure into SHLS format
shls_string = encoder.encode(data)

# Print the encoded SHLS string to the console
print(shls_string)