"""
This file was created by Sebastian Gruenwald on 14.11.2024, Neuhausen am Rheinfall.

Contact:
  - Email: sebiscodes@gmail.com

Social Links:
  - GitHub: https://github.com/sebiscodes
  - Instagram: https://www.instagram.com/sebisprojects/
  - YouTube: https://www.youtube.com/@sebisprojects
  - Linktree: https://linktr.ee/sebisprojects

Note: Comments were generated by ChatGPT
"""

from SHLSDecoder import SHLSDecoder # Import the SHLSDecoder class

# Example SHLS string to be decoded
# This string represents hierarchical data using indentation levels to indicate structure
shls_string = """
Company
 ID
 Name
 Founded
 Location
 Departments
  DepartmentID
  DepartmentName
  Employees
   EmployeeID
   Name
   Role
   Salary
   StartDate
   FullTime
   
Financials
 Year
 Revenue
 Expenses
 NetProfit

Company
 1001
 Tech Solutions Inc.
 2008
 New York, USA
 Departments
 
  001
  Development
  Employees
  
   1001
   Alice Smith
   Software Engineer
   90000
   2019-06-01
   true
   
   1002
   Bob Johnson
   Data Scientist
   95000
   2020-02-15
   true
   
  002
  Human Resources
  Employees
  
   2001
   Carol White
   HR Specialist
   60000
   2021-09-10
   true
   
   2002
   David Brown
   Recruiter
   55000
   2018-11-05
   false
   
Financials
 2021
 5000000
 3500000
 1500000
 
 2022
 5200000
 3700000
 1500000
"""
# Initialize the SHLSDecoder
# The decoder is responsible for parsing the SHLS string and extracting structured data
decoder = SHLSDecoder()

# Decode the SHLS string
# The decode method processes the SHLS input, creates templates for the structure,
# and extracts the associated data into a Python dictionary
templates = decoder.decode(shls_string)

# Print the resulting structured data
# This output shows the hierarchical data extracted from the SHLS string
print("Erstellte Templates:\n", templates)